version: '3.8'
services:
  stats-server:
    build: ./stats/stats-svc
    image: stats_svr_image
    container_name: stats_svr_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=stats_db
      - POSTGRES_USER=stats_user
      - POSTGRES_PASSWORD=stats_password
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db_container
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=stats_user
      - POSTGRES_PASSWORD=stats_password

  ewm-service:
    build: ./ewm-svc
    image: ewm_svc_image
    container_name: ewm_svc_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - DB_NAME=ewm_db
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=ewm_password
      - DB_HOST=ewm-db
      - DB_PORT=5432

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=ewm_password